# Generated by Django 5.1 on 2024-11-06 11:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Textwriter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=20)),
                ("coverImage", models.ImageField(upload_to="")),
                ("blog_desc", tinymce.models.HTMLField()),
            ],
        ),
    ]
