# Generated by Django 5.1 on 2024-11-06 20:37

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0002_categories_delete_catagories"),
        ("textwriter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textwriter",
            name="blog_desc",
        ),
        migrations.AddField(
            model_name="textwriter",
            name="Book_category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.categories",
            ),
        ),
        migrations.AddField(
            model_name="textwriter",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="textwriter",
            name="post_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
