# Generated by Django 5.1 on 2024-11-06 21:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "textwriter",
            "0002_remove_textwriter_blog_desc_textwriter_book_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="textwriter",
            name="body",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
