# Generated by Django 5.1 on 2024-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textwriter", "0004_alter_textwriter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textwriter",
            name="coverImage",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
